apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vk51
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0066-tenant/ci1t-43256-0066-app/devfile-sample-vk51@sha256:cda0715d9bd3cc490df3604f35c5842e381611ccdea4cf38df4963b33e66523e
        name: my-nodejs
        resources: {}
status: {}
