apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vk51
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vk51
    app.kubernetes.io/part-of: ci1t-43256-0066-app
  name: devfile-sample-vk51
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vk51
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vk51
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0066-tenant/ci1t-43256-0066-app/devfile-sample-vk51@sha256:cda0715d9bd3cc490df3604f35c5842e381611ccdea4cf38df4963b33e66523e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
